### ISSUE TITLE
Problem getting this to work

### ISSUE THREAD

**Issue by Glocktober** [jay-g-mehta/pydhcpdparser#1]
Following the instructions for 0.8 I could not get this to work.
using the example I get 

>>> print pydhcpdparser.parse(conf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'parse'

It appears to have changed from "parse" to "parser" - but that fails as well:

>>> print pydhcpdparser.parser(conf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: LRParser instance has no __call__ method

**Comment by jay-g-mehta** [comment]
Thanks for pointing out the problem. This was mere a README update with correct usage.
More reference on how to use, please refer:
1. README
2. Any test case from test_dhcp_conf_parser.py
3. https://github.com/jay-g-mehta/dhcpstatus/blob/master/dhcpstatus/dhcp_status.py 

Since not a tech update, not releasing this as a new pypi release.
Closing this issue.
